[[rocminfo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bca3c74e146c154f70ac764deb7acbaa47080976"
libc = "glibc"
os = "linux"

    [[rocminfo.download]]
    sha256 = "6baebc015b0ace67ef7ab4f0a1e64b5a5d7d89b144987b79d7552182be8c75f4"
    url = "https://github.com/JuliaBinaryWrappers/rocminfo_jll.jl/releases/download/rocminfo-v5.4.4+0/rocminfo.v5.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[rocminfo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e609af4f812606244e242bc6e81c71124954803"
libc = "musl"
os = "linux"

    [[rocminfo.download]]
    sha256 = "f3732b2238b29f09645796a6a2821412d301a38e7162e4f0774aecee8e1d9750"
    url = "https://github.com/JuliaBinaryWrappers/rocminfo_jll.jl/releases/download/rocminfo-v5.4.4+0/rocminfo.v5.4.4.x86_64-linux-musl-cxx11.tar.gz"
