[[rocminfo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83ca28693f1d35742ce79a01ad20ca7aae4c971e"
libc = "glibc"
os = "linux"

    [[rocminfo.download]]
    sha256 = "0f937cde5b8858957741e45368aa59233acb1e7a98ef4ffe1219f37b6392c76a"
    url = "https://github.com/JuliaBinaryWrappers/rocminfo_jll.jl/releases/download/rocminfo-v4.2.0+0/rocminfo.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[rocminfo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07285bbdff48f890c9607f70af8b9029ec5c9eea"
libc = "musl"
os = "linux"

    [[rocminfo.download]]
    sha256 = "3bab99d06ab56a5dacb16190b11600d42d47d4c008e451a26ed431d49d7a297b"
    url = "https://github.com/JuliaBinaryWrappers/rocminfo_jll.jl/releases/download/rocminfo-v4.2.0+0/rocminfo.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
