# Autogenerated wrapper script for rocminfo_jll for x86_64-linux-gnu-cxx11
export rocm_agent_enumerator, rocminfo

using hsakmt_roct_jll
using hsa_rocr_jll
JLLWrappers.@generate_wrapper_header("rocminfo")
JLLWrappers.@declare_executable_product(rocm_agent_enumerator)
JLLWrappers.@declare_executable_product(rocminfo)
function __init__()
    JLLWrappers.@generate_init_header(hsakmt_roct_jll, hsa_rocr_jll)
    JLLWrappers.@init_executable_product(
        rocm_agent_enumerator,
        "bin/rocm_agent_enumerator",
    )

    JLLWrappers.@init_executable_product(
        rocminfo,
        "bin/rocminfo",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
